name: Build and Push Backend Image to Google Cloud Platform

on:
  push:
    branches: [main]

jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: 436-backend
      PROJECT_ID: true-audio-417208

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Google Cloud Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Set script permissions
        run: chmod +x ./scripts/deploy_db.sh

      - name: Deploy MongoDB VM
        run: ./scripts/deploy_db.sh
        env:
          DEFAULT_DB_USER: user
          DEFAULT_DB_PASSWORD: 123456
          DEFAULT_DB_HOSTNAME: server-db
          DEFAULT_DB_PORT: 27017
          DEFAULT_VM_ZONE: europe-west4-a
          DEFAULT_VM_TYPE: e2-medium
          DEFAULT_VM_MEMORY: 4GB
          DEFAULT_FIREWALL_RULE: allow-mongo

      - name: Build Docker Image
        run: docker build -t ${{ env.IMAGE_NAME }}:latest ./server

      - name: Automatic Tagging of Releases
        id: increment-git-tag
        run: |
          bash ./scripts/git_update.sh -v major

      - name: Configure Docker Client
        run: |
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet

      - name: Push Docker Image to Artifact Registry
        env:
          GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        run: |
          docker tag ${{ env.IMAGE_NAME }}:latest europe-west1-docker.pkg.dev/${{ env.PROJECT_ID }}/images/${{ env.IMAGE_NAME }}:latest
          docker tag ${{ env.IMAGE_NAME }}:latest europe-west1-docker.pkg.dev/${{ env.PROJECT_ID }}/images/${{ env.IMAGE_NAME }}:${{ env.GIT_TAG }}
          docker push europe-west1-docker.pkg.dev/${{ env.PROJECT_ID }}/images/${{ env.IMAGE_NAME }}:latest
          docker push europe-west1-docker.pkg.dev/${{ env.PROJECT_ID }}/images/${{ env.IMAGE_NAME }}:${{ env.GIT_TAG }}

      - name: Build Deployment on Cloud Run
        run: |
          gcloud run deploy ${{ env.IMAGE_NAME }} \
            --image=europe-west1-docker.pkg.dev/${{ env.PROJECT_ID }}/images/${{ env.IMAGE_NAME }}:${{ env.GIT_TAG }} \
            --platform=managed \
            --region=europe-west1 \
            --allow-unauthenticated
            --set-env-vars=MONGO_URI="mongodb://${{ env.DEFAULT_DB_USER }}:${{ env.DEFAULT_DB_PASSWORD }}@${{ env.DEFAULT_DB_HOSTNAME }}:${{ env.DEFAULT_DB_PORT }}",JWT_SECRET="secret"
